# Generated by Django 6.1.2 on 2026-10-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='categories',
            field=models.ManyToManyField(related_name='notes', to='categories.category'),
        ),
    ]
